Install build-essential
iasql/iasql-engine pull request #1698
Opened 2022-12-20 15:16 UTC by dfellis

2022-12-20 15:58 UTC, yrobla requested changes

2022-12-20 15:58 UTC, yrobla commented on Dockerfile
> +RUN apt install curl ca-certificates gnupg build-essential -y
you need to add git as well

2022-12-20 16:01 UTC, dfellis commented on Dockerfile
> +RUN apt install curl ca-certificates gnupg build-essential -y
```suggestion
RUN apt install curl ca-certificates gnupg build-essential git -y
```

2022-12-20 16:02 UTC, yrobla approved these changes

2022-12-20 16:03 UTC, merged

2022-12-21 05:55 UTC, mtp1376 reviewed
LGTM :D